version: "3.8"

services:
  bitcoin-cronjob:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true