version: '3.8'

services:
  bitcoin-cronjob:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kafka-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped


networks:
  kafka-net:
    external: true